### PR TITLE
GoTo plugin

### PR DESCRIPTION
**Pull request by andrelsm**
Adds Go To Line (ctrl-G) functionality, prompting and validating the target line number in a popup dialog.

### CODE REVIEW

**Comment by andrelsm** [comment]
hi, WebCoder,

my first plugin... Tested in Chromium and Firefox. Other browsers seems to implement the needed features for it to work.

GoTo plugin in action:
https://github.com/WebCoder49/code-input/assets/1190616/bb96923b-ab75-456b-898b-5828e723515f

best regards
andrelsm

**Comment by WebCoder49** [comment]
Thank you so much for this! I should hopefully be able to test, merge, and release this by tomorrow! (Friday 2023-12-08 evening UTC).

**Comment by WebCoder49** [comment]
As I spent quite a while on the Ctrl+F bug, I'm afraid I won't have time to release this today, but the only step left for me is fully testing this and setting the version so it should be ready by Monday.

**Comment by andrelsm** [comment]
take it easy...

**Comment by WebCoder49** [comment]
@andrelsm Thank you!

Thanks also for all of your contributions just now - I am afraid that I had less free time today than I thought but should be able to get this implemented and hopefully start on the other issues soon next week.

**Pull request merged**
